### ISSUE TITLE
lacrosse view  blocking call 

### ISSUE THREAD

**Issue by xenia-09A** [IceBotYT/lacrosse_view#6]
Hello thanks for doing this prior is anyone else maintaining this code?
if not I guess I best to find a new solution on HA?
thanks!!!

I have some issues on HA with blocking

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 6:53:58 AM (1 occurrences)
Last logged: 6:53:58 AM

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by integration 'lacrosse_view' at homeassistant/components/lacrosse_view/coordinator.py, line 65: sensors = await self.api.get_sensors( (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+lacrosse_view%22 For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/usr/src/homeassistant/homeassistant/components/lacrosse_view/__init__.py", line 36, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/components/lacrosse_view/coordinator.py", line 65, in _async_update_data sensors = await self.api.get_sensors(

**Comment by IceBotYT** [comment]
Fixed in v1.0.2

**Comment by xenia-09A** [comment]
thanks so much for taking your personal time to do this , since I have HA do I need to wait for them to update this 
integration?

**Comment by IceBotYT** [comment]
Yes, the fix will be in 2024.8.2.
